name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ARTIFACT_NAME: jenkins-demo-snapshot
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ARTIFACT_NAME}}:$(date +%s)

    - name: Save docker image
      run: docker save ${{ARTIFACT_NAME}}:$(date +%s) -o ${{ARTIFACT_NAME}}.tar
    
    - name: upload the image
      uses: actions/upload-artifact@v4
      with:
        name: ${{ARTIFACT_NAME}}
        path: ${{ARTIFACT_NAME}}.tar
