name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build and save Docker image
      run: |
        IMAGE_NAME="jenkins-demo-image:$(date +%s)"
        docker build . --file Dockerfile --tag $IMAGE_NAME
        ARTIFACT_NAME="jenkins-demo-image-$(date +%s)"
        docker save $IMAGE_NAME -o ARTIFACT_NAME.tar
        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
    
    - name: upload the image
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}.tar
        path: ${{ env.ARTIFACT_NAME }}.tar
