name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build and save Docker image
      run: |
        docker build . --file Dockerfile --tag jenkins-demo:latest
        docker save jenkins-demo:latest -o jenkins-demo-image.tar
    
    - name: upload the image
      uses: actions/upload-artifact@v4
      with:
        name: jenkins-demo-image.tar
        path: jenkins-demo-image.tar
